version: '3'
services:
  sandbox-postgres:
    build:
      context: dbase
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=POSTGRES_USER
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
      - POSTGRES_DB=POSTGRES_DB

  api:
    image: yannarbt/hublo-exercise:latest
    ports:
      - '3001:3001'
    environment:
      - DATABASE_URL="postgres://POSTGRES_USER:POSTGRES_PASSWORD@localhost:5432/POSTGRES_DB"
    depends_on:
      - sandbox-postgres